[project]
name = "greprag"
version = "0.1.0"
description = "Search and summarization agent for texts"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv==1.2.1",
    "ruff>=0.14.10",
    "openai>=2.14.0",
    "aiolimiter>=1.1.0",
    "sentry-sdk>=2.48.0",
]
